// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using web_kursachsem4.Data;

#nullable disable

namespace web_kursachsem4.Data.Migrations
{
    [DbContext(typeof(mainDBcontext))]
    [Migration("20250419093422_Database01")]
    partial class Database01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("web_kursachsem4.Data.Models.Levels", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("CompletedLevels")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("web_kursachsem4.Data.Models.Score", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreValue")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("web_kursachsem4.Data.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("web_kursachsem4.Data.Models.Levels", b =>
                {
                    b.HasOne("web_kursachsem4.Data.Models.User", "User")
                        .WithOne("Levels")
                        .HasForeignKey("web_kursachsem4.Data.Models.Levels", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("web_kursachsem4.Data.Models.Score", b =>
                {
                    b.HasOne("web_kursachsem4.Data.Models.User", "User")
                        .WithOne("Score")
                        .HasForeignKey("web_kursachsem4.Data.Models.Score", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("web_kursachsem4.Data.Models.User", b =>
                {
                    b.Navigation("Levels");

                    b.Navigation("Score");
                });
#pragma warning restore 612, 618
        }
    }
}
