// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using web_kursachsem4.Data;

#nullable disable

namespace web_kursachsem4.Data.Migrations
{
    [DbContext(typeof(mainDBcontext))]
    [Migration("20250412205141_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("web_kursachsem4.Data.Models.Levels", b =>
                {
                    b.Property<int>("userid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("userid"));

                    b.PrimitiveCollection<List<bool>>("lvl")
                        .HasColumnType("boolean[]");

                    b.Property<int>("userid1")
                        .HasColumnType("integer");

                    b.HasKey("userid");

                    b.HasIndex("userid1");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("web_kursachsem4.Data.Models.Score", b =>
                {
                    b.Property<int>("userid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("userid"));

                    b.Property<int>("score")
                        .HasColumnType("integer");

                    b.Property<int>("userid1")
                        .HasColumnType("integer");

                    b.HasKey("userid");

                    b.HasIndex("userid1");

                    b.ToTable("Score");
                });

            modelBuilder.Entity("web_kursachsem4.Data.Models.User", b =>
                {
                    b.Property<int>("userid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("userid"));

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .HasColumnType("text");

                    b.HasKey("userid");

                    b.ToTable("User");
                });

            modelBuilder.Entity("web_kursachsem4.Data.Models.Levels", b =>
                {
                    b.HasOne("web_kursachsem4.Data.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userid1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("web_kursachsem4.Data.Models.Score", b =>
                {
                    b.HasOne("web_kursachsem4.Data.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userid1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });
#pragma warning restore 612, 618
        }
    }
}
